import { htmlText as h } from '../content/text';
import { MAX_LENGTH } from '../security/policy';
export function restoreTemplate():string {
  return `<section id="restore-screen" class="restore-screen" role="main" aria-label="${h('restore.title')}" hidden>
  <div class="workbar restore-workbar"><button id="restore-run" class="primary" disabled>${h('restore.run')}</button><p id="restore-status" role="status" aria-live="polite">${h('restore.ready')}</p><button id="restore-clear" class="quiet">${h('restore.clear')}</button></div>
  <div class="workspace restore-workspace">
    <section class="panel"><div class="section-heading"><span class="step-number">01</span><h2>${h('restore.inputTitle')}</h2></div><p class="panel-caption">${h('restore.inputHint')}</p><div class="text-pane"><textarea id="restore-input" aria-label="${h('restore.inputTitle')}" maxlength="${MAX_LENGTH}" spellcheck="false" placeholder="${h('restore.inputPlaceholder')}"></textarea></div><div class="panel-footer"><span class="hint" id="restore-length">${h('input.length',{count:0,max:MAX_LENGTH})}</span></div></section>
    <section class="panel"><div class="section-heading"><span class="step-number">02</span><h2>${h('restore.mappingTitle')}</h2></div><div class="restore-map-actions"><button id="restore-use-current" disabled>${h('restore.useCurrent')}</button><button id="restore-import">${h('restore.import')}</button><input id="restore-file" type="file" accept=".csv,text/csv" aria-label="${h('restore.import')}" hidden></div><p id="restore-map-source" class="panel-caption">${h('restore.noMapping')}</p><label id="restore-legacy" class="restore-legacy" hidden><input id="restore-legacy-check" type="checkbox">${h('restore.legacy')}</label><div class="table-scroll"><table class="data-table restore-table"><colgroup><col class="restore-token-col"><col><col class="col-total"></colgroup><thead><tr><th scope="col">${h('column.replacement')}</th><th scope="col">${h('restore.original')}</th><th scope="col">${h('restore.count')}</th></tr></thead><tbody id="restore-mappings"></tbody></table><p id="restore-empty" class="empty-state">${h('restore.mappingHint')}</p></div><div class="panel-footer"><span class="hint">${h('restore.snapshotHint')}</span></div></section>
    <section class="panel output-panel"><div class="section-heading"><span class="step-number">03</span><h2>${h('restore.outputTitle')}</h2></div><div class="output-actions"><button id="restore-copy" class="primary" disabled>${h('button.copy')}</button><button id="restore-txt" disabled>${h('button.txt')}</button></div><div class="text-pane"><textarea id="restore-output" readonly aria-label="${h('restore.outputTitle')}" placeholder="${h('restore.outputPlaceholder')}"></textarea></div><p id="restore-feedback" class="copy-feedback" role="status" aria-live="polite"></p><div class="panel-footer"><span class="hint">${h('restore.sensitive')}</span></div></section>
  </div><div class="statusbar"><p>${h('restore.exact')}</p><span>${h('restore.memory')}</span></div></section>`;
}
