import { restoreTemplate } from './restore-template';
import { htmlText } from '../content/text';
import { appBase } from '../model/config';
import { MAX_LENGTH } from '../security/policy';

export function appTemplate():string {
  return `<header class="app-header">
  <div class="brand"><img class="brand-icon" src="${new URL('favicon.svg',appBase()).href}" alt="" width="34" height="34"><div><span class="eyebrow">${htmlText("app.brand")}</span><h1>${htmlText("app.title")}</h1></div></div>
  <nav class="mode-switch" aria-label="${htmlText("mode.label")}"><button id="mode-mask" aria-pressed="true">${htmlText("mode.mask")}</button><button id="mode-restore" aria-pressed="false">${htmlText("mode.restore")}</button></nav>
  <div class="privacy-callout"><strong>${htmlText("privacy.heading")}</strong><span>${htmlText("privacy.short")}</span></div>
  <button id="help-open" aria-haspopup="dialog" aria-controls="help-dialog">${htmlText("button.help")}</button>
</header>
<div id="mask-workbar" class="workbar"><details id="category-filter" class="category-filter"><summary>${htmlText("filter.label")}<span id="category-filter-count">${htmlText("filter.all")}</span></summary><div class="category-menu"><div class="category-tools"><button type="button" id="select-all-categories">${htmlText("button.selectAll")}</button><button type="button" id="clear-all-categories">${htmlText("button.clearAll")}</button></div><div id="category-options" class="category-options" role="group" aria-label="${htmlText("filter.label")}"></div></div></details><div class="check-action"><button id="check" class="primary" aria-describedby="check-status">${htmlText("button.check")}</button><button id="check-ai" aria-describedby="check-status">${htmlText("button.checkAi")}</button><p id="check-status" role="status" aria-live="polite"></p></div></div>
<main id="mask-workspace" class="workspace">
<section class="panel input-panel" aria-labelledby="input-title"><div class="section-heading"><span class="step-number">${htmlText("step.input")}</span><h2 id="input-title">${htmlText("input.title")}</h2><button id="clear" class="quiet">${htmlText("button.clear")}</button></div>
<div class="view-switch-label">${htmlText("view.switch")}<span>${htmlText("view.hint")}</span></div><div class="input-tabs" role="tablist" aria-label="${htmlText("view.label")}"><button id="tab-edit" role="tab" aria-selected="true" aria-controls="edit-pane">${htmlText("view.edit")}</button><button id="tab-review" role="tab" aria-selected="false" aria-controls="review-pane" tabindex="-1">${htmlText("view.review")}</button><span id="length">${htmlText("input.length",{count:0,max:MAX_LENGTH})}</span></div>
<div id="edit-pane" class="text-pane" role="tabpanel" aria-labelledby="tab-edit"><textarea id="source" aria-label="${htmlText("input.title")}" maxlength="${MAX_LENGTH}" spellcheck="false" placeholder="${htmlText("input.placeholder")}"></textarea></div>
<div id="review-pane" class="text-pane" role="tabpanel" aria-labelledby="tab-review" hidden><div id="highlight" class="preview" tabindex="0" aria-label="${htmlText("view.highlightLabel")}"></div></div>
<div class="panel-footer manual-add"><span id="selected-text" class="selected-text">${htmlText("manual.prompt")}</span><button id="manual" disabled>${htmlText("button.manual")}</button></div></section>
<section class="panel candidate-panel" id="results" aria-labelledby="candidate-title"><div class="section-heading"><span class="step-number">${htmlText("step.review")}</span><h2 id="candidate-title">${htmlText("candidates.title")}</h2></div><p id="count" class="panel-caption">${htmlText("candidates.summary",{groups:0,count:0})}</p><div class="table-scroll"><table class="data-table candidates-table"><colgroup><col class="col-check"><col class="col-original"><col class="col-replacement"><col class="col-category"><col class="col-total"></colgroup><thead><tr><th scope="col">${htmlText("column.enabled")}</th><th scope="col">${htmlText("column.original")}<small>${htmlText("column.method")}</small></th><th scope="col">${htmlText("column.replacement")}</th><th scope="col">${htmlText("column.category")}</th><th scope="col" title="${htmlText("column.countTitle")}">${htmlText("column.count")}<small>${htmlText("column.countDetail")}</small></th></tr></thead><tbody id="candidates"></tbody><tfoot><tr><th scope="row" colspan="4">${htmlText("candidates.total")}</th><td id="replacement-total">${htmlText("candidates.zero")}</td></tr></tfoot></table><p id="candidates-empty" class="empty-state">${htmlText("candidates.empty")}<br>${htmlText("status.ready")}</p></div><p id="mapping-feedback" class="copy-feedback" role="status" aria-live="polite"></p><div class="panel-footer candidate-actions"><span class="hint">${htmlText("mapping.warning")}</span><button id="copy-mapping" disabled>${htmlText("button.copyMapping")}</button><button id="download-mapping" disabled>${htmlText("button.csv")}</button></div></section>
<section class="panel output-panel" aria-labelledby="output-title"><div class="section-heading"><span class="step-number">${htmlText("step.output")}</span><h2 id="output-title">${htmlText("output.title")}</h2></div><div class="output-actions"><button id="copy" class="primary">${htmlText("button.copy")}</button><button id="download-txt">${htmlText("button.txt")}</button></div><button id="open-restore-current" class="restore-link" disabled>${htmlText("restore.link")}</button><p id="output-warning" class="output-warning" role="alert" hidden>${htmlText("output.unmasked")}</p><div class="text-pane"><textarea id="output" readonly aria-label="${htmlText("output.label")}" placeholder="${htmlText("output.placeholder")}"></textarea></div><p id="copy-feedback" class="copy-feedback" role="status" aria-live="polite"></p><div class="panel-footer"><span class="hint">${htmlText("output.review")}</span></div></section>
</main><footer id="mask-statusbar" class="statusbar"><p id="status" role="status">${htmlText("status.ready")}</p><span>${htmlText("privacy.limit")}</span></footer>
${restoreTemplate()}
<dialog id="help-dialog" aria-labelledby="help-title"><div class="help-shell"><div class="help-heading"><h2 id="help-title">${htmlText("help.title")}</h2><button id="help-close" aria-label="${htmlText("help.closeLabel")}">${htmlText("button.close")}</button></div><div class="help-content"><p class="help-privacy">${htmlText("privacy.notice")}</p><ol><li><strong>${htmlText("help.step1.title")}</strong><p>${htmlText("help.paragraph01")}</p></li><li><strong>${htmlText("help.step2.title")}</strong><p>${htmlText("help.paragraph02")}</p></li><li><strong>${htmlText("help.step3.title")}</strong><p>${htmlText("help.paragraph03")}</p></li><li><strong>${htmlText("help.step4.title")}</strong><p>${htmlText("help.paragraph04")}</p></li></ol><h3>${htmlText("help.settings.title")}</h3><p>${htmlText("help.paragraph05")}</p><p>${htmlText("help.paragraph06")}</p><p>${htmlText("help.paragraph07")}</p><h3>${htmlText("help.restore.title")}</h3><p>${htmlText("help.restore.body")}</p><h3>${htmlText("help.model.title")}</h3><p>${htmlText("help.paragraph08")}</p><p class="hint">${htmlText("help.paragraph09")}</p></div></div></dialog>
`;
}
